version: '3'

services:
  redis:
    image: redis
    container_name: "redis-container"
    restart: "always"
    volumes:
      - ./.dbcache/redis/data:/data/db
    ports:
      - "6379:6379"
    networks:
      - backend

  mongo:
    image: mongo
    container_name: "mongodb-container"
    restart: "always"
    volumes:
      - ./.dbcache/mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  legacy-api:
    container_name: api-legacy-container
    build:
      context: .
      dockerfile: api-legacy/Dockerfile
    restart: always
    command: npm start
    ports:
      - "3333:3333"
    networks:
      - backend

  data-integration-api:
    container_name: data-integration-container
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - JWT_SECRET=s3cr3ts4uc3
      - ENCRYPT_SECRET=sup3rs3cr3t
    volumes:
      - .:/usr/src/data-integration
    depends_on:
      - mongo
      - legacy-api
    networks:
      - backend
    command: go run cmd/data-integration/main.go

networks:
  backend:
    driver: "bridge"
