version: '3'

services:
  mongo:
    image: mongo
    container_name: "mongodb-container"
    restart: "always"
    volumes:
      - ./.dbcache/mongo/data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend

  legacy-api:
    container_name: api-legacy-container
    build: 
      context: .
      dockerfile: api-legacy/Dockerfile
    restart: always
    command: npm start
    volumes: 
      - ./api-legacy:/usr/src/legacy-api
    ports: 
      - "3333:3333"
    networks: 
      - backend

networks:
  backend:
    driver: "bridge"